### ISSUE TITLE
Improve Mainpage

### ISSUE THREAD

**Issue by Thaodan** [tworaz/sailfish-ytplayer#13]
What about moving everything than the selected main page to a pully menu?
So that for example: Recommed for me is on the main page.
Account stuff is on the second page if you swipe to the left or right.

**Comment by tworaz** [comment]
Personally I don't like this idea. Moving options from the MainMenu page into a pulley menu would  be agains sailfish guidelines. 3-4 options in pulley is ok, anything more than that is bad, see: https://sailfishos.org/sailfish-silica/sailfish-application-pitfalls.html. This is even more true considering the fact that I have at least 3 more options in mind for the main menu. At that point having all menu options available via top pulley will be simply unusable.

Of course if you can present a better design for the main page which could replace current MainMenu and would not involve crowded pulleys and lots of attached pages I'd be happy to consider it.

**Comment by Thaodan** [comment]
Am Mittwoch, 14. Januar 2015, 15:33:43 schrieb Peter Tworek:
> Personally I don't like this idea. Moving options from the MainMenu page
> into a pulley menu would  be agains sailfish guidelines. 3-4 options in
> pulley is ok, anything more than that is bad, see:
> https://sailfishos.org/sailfish-silica/sailfish-application-pitfalls.html.
> This is even more true considering the fact that I have at least 3 more
> options in mind for the main menu. At that point having all menu options
> available via top pulley will be simply unusable.
Was just an first idea But search for example is an good item for the pulley 
menu, settings too.
Than video categorie on the left page und the account stuff on the right and 
move about as pully menu to settings?
> Of course if you can present a better design for the main page which could
> replace current MainMenu and would not involve crowded pulleys and lots of
> attached pages I'd be happy to consider it.
Yeah I was thinking of this but my coding skills in C++ are not very good and 
I first wanted to post this here.

**Comment by tworaz** [comment]
# Was just an first idea But search for example is an good item for the pulley menu, settings too.

Not necessarily. Global search available through main menu IMO does not belong in the pulley menu. Contextual searches (searches limited only to content presented in the currently active page) do. I have a plan to add support for them in 0.5.0.

# Than video categorie on the left page und the account stuff on the right and move about as pully menu to settings?

I don't like that approach. Pulley menus as the name suggests are just menus. They are not supposed to take an active part in app navigation. They are supposed to perform some action in the context of the currently active page. For example it's fine to show a channel browser page for a patricular video. The channel video is always strictly related to a channel it belongs to. Once you start using pulleys to switch between unrelated pages (Video categories -> global search) it all becomes a mess.

I can agree that settings and about pages can, and probably should be moved to top pulley in main menu. They're still part of of the main menu because I don't like having extra empty space at the bottom of main menu page. Once additional options make their way into the page I'll move them.

# Yeah I was thinking of this but my coding skills in C++ are not very good and I first wanted to post this here.

No need to code, flow diagrams or mockups are also fine. It's often hard to understand and more importantly implement features like you're propsing based just on 2 sentence description :)

On a sidenote the entire UI of YTPlayer is written in QML. C++ is only used for lower level logic.

**Comment by tworaz** [comment]
Main menu structure was changed for 0.5.0 release in 7733a1514612d57c17a3745ec4edc27f93ddbe4c.
