### ISSUE TITLE
Latest subscribed videos not shown correctly

### ISSUE THREAD

**Issue by Termitebug** [tworaz/sailfish-ytplayer#52]
Somewhat has changed with Youtube:

`Account page activated, state: SUBSCRIPTION_VIDEOS
YouTube request method:  "list" , resource:  "activities" , params:  QMap(("home", QVariant(bool, true) ) ( "part" ,  QVariant(QString, "id,snippet,contentDetails") ) )  
Selected item is a video, opening video overview page
Video overview page for video ID: hNqJvVCMoxE created
YouTube request method:  "list" , resource:  "videos" , params:  QMap(("id", QVariant(QString, "hNqJvVCMoxE") ) ( "part" ,  QVariant(QString, "snippet,contentDetails,statistics") ) )  
YouTube request method:  "list" , resource: "videos/getRating" , params:  QMap(("id", QVariant(QString, "hNqJvVCMoxE") ) )  
Changing cover to: VideoOverview.qml`

So YouTube request method:  "list" , resource: "videos/getRating" should be something else. 
How do I can change that?

**Comment by a-andreyev** [comment]
The problem is that youtube home activity APIv3 method that is used for the subscriptions videos is now returning some default youtube top videos b******t.
And it's a [pain](http://stackoverflow.com/questions/19640796/retrieving-all-the-new-subscription-videos-in-youtube-v3-api/23620166#23620166) to implement it manually right now.
I will try to find some time to take a look at this, but could not promise anything.
